import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Page from "../layouts/Page";
import { CameraIcon } from "@heroicons/react/20/solid";

const About: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Web Forestry – About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="overflow-hidden">
          <div className="relative max-w-7xl mx-auto py-24 px-4 sm:px-6 lg:px-8">
            <div className="hidden lg:block bg-gray-50 absolute top-0 bottom-0 left-3/4 w-screen" />
            <div className="mx-auto text-base max-w-prose lg:grid lg:grid-cols-2 lg:gap-8 lg:max-w-none">
              <div>
                <div>
                  <span className="rounded bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-500 tracking-wide uppercase">
                    Our origin story
                  </span>
                </div>
                <h2 className="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                  Web Forestry lets you focus on growing your business
                </h2>
              </div>
            </div>
            <div className="mt-8 lg:grid lg:grid-cols-2 lg:gap-10">
              <div className="relative lg:row-start-1 lg:col-start-2">
                <svg
                  className="hidden lg:block absolute top-0 right-0 -mt-20 -mr-20"
                  width={404}
                  height={384}
                  fill="none"
                  viewBox="0 0 404 384"
                  aria-hidden="true"
                >
                  <defs>
                    <pattern
                      id="de316486-4a29-4312-bdfc-fbce2132a2c1"
                      x={0}
                      y={0}
                      width={20}
                      height={20}
                      patternUnits="userSpaceOnUse"
                    >
                      <rect
                        x={0}
                        y={0}
                        width={4}
                        height={4}
                        className="text-gray-200"
                        fill="currentColor"
                      />
                    </pattern>
                  </defs>
                  <rect
                    width={404}
                    height={384}
                    fill="url(#de316486-4a29-4312-bdfc-fbce2132a2c1)"
                  />
                </svg>
                <div className="relative text-base mx-auto max-w-prose lg:max-w-none">
                  <figure>
                    <div className="aspect-w-12 aspect-h-7 lg:aspect-none">
                      <img
                        className="rounded-lg shadow-lg object-cover object-center"
                        src="https://images.unsplash.com/photo-1473448912268-2022ce9509d8?ixlib=rb-1.2.1&auto=format&fit=crop&crop=focalpoint&fp-x=.735&fp-y=.55&w=1184&h=1376&q=80"
                        alt="Whitney leaning against a railing on a downtown street"
                        width={1184}
                        height={1376}
                      />
                    </div>
                    <figcaption className="mt-3 flex text-sm text-gray-500">
                      <CameraIcon
                        className="flex-none w-5 h-5 text-gray-400"
                        aria-hidden="true"
                      />
                      <span className="ml-2">Photograph by Luca Bravo</span>
                    </figcaption>
                  </figure>
                </div>
              </div>
              <div className="mt-8 lg:mt-0">
                <div className="text-base max-w-prose mx-auto lg:max-w-none">
                  <p className="text-lg text-gray-500">
                    In the summer of 2020, Dinklage Feed Yards was in dire need
                    of a website developer when the Wordpress website powering
                    their business went down suddenly. Their existing website
                    provider was unable to assist them, and the company was
                    stuck.
                  </p>
                </div>
                <div className="mt-5 prose prose-emerald text-gray-500 mx-auto lg:max-w-none lg:row-start-1 lg:col-start-1">
                  <p>
                    After debugging through the site, the problem was quickly
                    resolved and Dinklage Feed Yards was back in business. After
                    taking a quick look at the functioning site, it was clear
                    that there was other low hanging fruit that would improve
                    the website – not only for Dinklage Feed Yards customers but
                    also for employees at Dinklage managing the site.
                  </p>
                  <br />
                  <p>
                    Fast forward to the spring of 2022. Dinklage was no stranger
                    as they continued to request one-off website maintenance
                    over the years, but this time they needed more than
                    maintenance. Their site was down completely, and they were
                    <i> having trouble communicating</i> with the developer that
                    they had worked with to build the site initially. After
                    finally hearing back from the developer, a website hosting
                    misunderstanding resulted in Dinklage Feed Yards to be back
                    at square zero with their website.
                  </p>
                  <br />
                  <p>That&apos;s where we came in.</p>
                  <br />
                  <p>
                    Within 30 days, we completely rebuilt the Dinklage Feed
                    Yards website from the ground up, using cutting-edge
                    technologies that are capable of growing with Dinklage.
                    Within 60 days, the new website boasted feature parity of
                    the original website, and also added a new web-based job
                    application form allowing Dinklage to accept applications
                    for their job postings online. We also enabled Dinklage with
                    custom content management features so that they can edit
                    their website content, manage job postings, maintain feed
                    yard contacts, and more.
                  </p>
                  <br />
                  <p>
                    Through working with Dinklage Feed Yards, our eyes were
                    opened to this one point:{" "}
                    <strong>
                      Your business deserves a website and developers that grow
                      with you.
                    </strong>
                  </p>
                  <br />
                  <p>
                    Here at Web Forestry, we are committed to helping businesses
                    like Dinklage Feed Yards – so that you can focus on your
                    business and know we&apos;ll never leave you hanging.
                    We&apos;ll take the reigns of your website, and remain by
                    your side as long as you want us on your team.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Page>
  );
};

export default About;
